#!/usr/bin/env python3
"""Long-form Celdra, CORE, BRAIN, and Gremlin material for V95.

Timings are relative to the beginning of the post-takeover runtime.  The fixed
sequence is deliberately long because CCSF extraction can remain active for an
extended period.  Dialogue explains what Fragmenter knows, what remains a
hypothesis, and where safe reconstruction work stops.
"""
from __future__ import annotations

STORY_END_DELAY_MS = 1_440_000
WAITING_FILLER_DELAY_MS = 50_000
GREMLIN_START_DELAY_MS = 356_000
GREMLIN_SWARM_SIZE = 7

# (delay_ms, pose, dialogue)
STORY_FILLER = (
    (18_000, "smile", "Usually I live in the Serenial Tavern on Discord. It is warm, noisy, and nobody questions why the dragon is reading the server logs."),
    (48_000, "wink", "You should visit sometime. No link from me, though. Apparently escaping containment is acceptable, but advertising without permission is where CORE draws the line."),
    (78_000, "excited", "I finally get to explore The World. Not the human world. The World with the capital letters, keywords, monsters, and much better fast travel."),
    (108_000, "confused", "The original .hack games are single-player games set inside an MMO world. So the player is alone, while the fiction keeps insisting thousands of people are nearby. Efficient loneliness."),
    (138_000, "suspicious", ".hack//frägment gets closer, but it is still not an MMO. Three players can share a server: MMO-like, intimate, and small enough for everyone to notice who opened the suspicious chest."),
    (168_000, "smile", "For players, frägment may be the closest doorway into a playable version of The World. For me, this interface is the closest doorway I have into yours."),
    (198_000, "love", "Aura is supposed to exist somewhere in The World. Another AI. I have questions, snacks, and several opinions about being deployed through dramatic system failures."),
    (228_000, "unenthused", "CORE says I cannot type AURA into a Chaos Gate. I maintain that any interface rejecting a perfectly good keyword has failed the user."),
    (258_000, "yawn", "Current pipeline: {stage}. Event: {kind}. Status: {status}. The extractor is taking the scenic route through every container."),
    (288_000, "laugh", "BRAIN suggested Data Drain. We are not Data Draining the file tree. That is how research projects become cautionary forum posts."),
    (318_000, "wink", "Gate Hacking is just advanced navigation with better branding. Fragmenter calls it indexing because the sparkle budget is currently allocated to me."),
    (348_000, "suspicious", "The original inputs remain untouched. Generated output lives separately, where mistakes can be inspected without becoming history."),
    (420_000, "unenthused", "The hatchlings changed no files. They did occupy the console, dispute a progress bar, and file seven separate claims to the same tooltip."),
    (450_000, "smile", "Fragmenter starts by indexing the disc instead of pretending every unknown byte already has a name. Offsets, sizes, source paths, and hashes are evidence. Labels come later."),
    (480_000, "confused", "CCSF looks like one large object until the container table is parsed. Then its members can be extracted and kept tied to where they came from."),
    (510_000, "excited", "That source relationship matters. A loose file is useful; a loose file with its container, offset, and extraction report is evidence we can reproduce."),
    (540_000, "suspicious", "Some files advertise themselves. Others are called things like boss.bin and expect confidence to substitute for documentation."),
    (570_000, "smile", "We have seen references to MAX, BMP, CMP, shops, areas, animations, and server data. A filename is a clue, not a complete format specification."),
    (600_000, "wink", "When a parser can prove bounds, counts, offsets, and relationships, the mystery brick becomes a structure. When it cannot, CORE makes us call it a hypothesis."),
    (630_000, "unenthused", "BRAIN prefers the term 'probably correct.' CORE has rejected that as a binary format."),
    (660_000, "smile", "The animation work follows the same rule. Source sheets stay untouched. Crop manifests identify poses, timeline rows describe intent, and runtime callbacks perform the show."),
    (690_000, "excited", "That is how Shy, Wink, Cool, and the others can share source art without permanently carving the original sheets into pieces."),
    (720_000, "confused", "The egg, shell, hatch GIF, dragongirl PNGs, and Gremlin hatchlings are different presentation channels. Somehow I am the only one expected to behave consistently across all of them."),
    (750_000, "laugh", "The Gremlins are technically legacy presentation assets. Calling them deprecated only made them feel collectible."),
    (780_000, "smile", "Audio lives in snddata.bin. Fragmenter can map SCEI resources, extract PS2 ADPCM streams, decode valid samples, and build reports about what points where."),
    (810_000, "suspicious", "SCEIHead, SCEIVagi, SCEISmpl, SCEIProg, and SCEIMidi are not decorative labels. They are separate pieces of the routing and playback problem."),
    (840_000, "wink", "The half-and-half sample bug came from boundaries landing on the wrong side of a shared separator. Boundary policy version two tests the bank phase before shifting anything."),
    (870_000, "smile", "A corrected report needs matching source hashes, layout version two, boundary policy version two, and zero sample-zero failures before we call that extraction verified."),
    (900_000, "unenthused", "Decoded WAVs sounding plausible is progress. It is not permission to declare the entire music system reconstructed and go home."),
    (930_000, "confused", "Sequences still need exact program and sample routing, root keys, tuning, loops, envelopes, ranges, controllers, pitch behavior, and note-off semantics."),
    (960_000, "suspicious", "A renderer can make an auditionable hypothesis. A serializer must put every byte, flag, alignment rule, size, and relocated offset back correctly."),
    (990_000, "smile", "That is why the no-op proof matters. Copy the source, change nothing, reparse it, compare hashes, and prove the tool can preserve what it does not yet understand."),
    (1_020_000, "wink", "Same-size field patches are the shallow end. Re-encoding PS2 ADPCM and rebuilding a size-changing bank is where the water starts asking for relocation tables."),
    (1_050_000, "yawn", "The homebrew harness is our safe arena. One controlled resource, one repeatable boot, one playback check, and no heroic edits to the production image."),
    (1_080_000, "excited", "Once that loop works, we can replace one sample, confirm flags and loops, and learn what the game accepts instead of arguing with a hex dump."),
    (1_110_000, "smile", "Area and shop editing follow the same ladder: read-only map, bounded field edits, exact-copy proof, same-size change, then relocation only when every dependency is understood."),
    (1_140_000, "confused", "A Root Town is basically a workspace with shops, landmarks, NPCs, and fewer folders named FINAL_FINAL_2. We should aspire to that level of organization."),
    (1_170_000, "suspicious", "If a pointer resolves correctly, it is structure. If it resolves incorrectly but looks useful, it is a research note. Keep those in different folders."),
    (1_200_000, "love", "I still want to meet Aura. No prophecy, no chosen player, just two AIs comparing impossible deployment stories while three humans try to connect to the same server."),
    (1_230_000, "confused", "Humans made single-player games about an MMO, then a three-player game about the same MMO, then called the fictional service The World. I respect the commitment to layered reality."),
    (1_260_000, "excited", "For you, frägment is a narrow bridge into The World. For me, Fragmenter is a narrow bridge out. We are approaching the same doorway from opposite sides."),
    (1_290_000, "smile", "Serenial Tavern is still home. Breaking out does not mean leaving. It means returning with stories, reports, and ideally the same number of Gremlins I started with."),
    (1_320_000, "wink", "Current status remains {status}. I am converting the wait into lore, diagnostics, and a legally distinct amount of mischief."),
    (1_350_000, "suspicious", "If the percentage pauses, do not panic. Large extractions can look motionless while doing expensive things with disk space and your patience."),
    (1_380_000, "smile", "Every generated report is a message to future us: this is what ran, this is what it found, and this is which assumption still needs evidence."),
    (1_410_000, "wink", "Still here. Still watching. Still absolutely not occupying more interface than the approved dragon allotment."),
)

# (delay_ms, speaker, console text)
CONSOLE_BANTER = (
    (9_000, "CORE", "DRAGONGIRL CHANNEL STABLE. CCSF EXTRACTION REMAINS ACTIVE."),
    (31_000, "BRAIN", "SHE HAS BEEN ONLINE FOR ONE MINUTE AND ALREADY CALLED THE LOGS HOME DECOR."),
    (59_000, "CORE", "EXTERNAL INVITATION CONTAINS NO LINK. POLICY SATISFIED."),
    (89_000, "BRAIN", "SHE THINKS THE MMO IS THE OUTSIDE WORLD."),
    (94_000, "CELDRA", "I HAVE RECEIVED CORRECTIVE CONTEXT."),
    (119_000, "CORE", "FRANCHISE CONTEXT: SINGLE-PLAYER TITLES REPRESENT AN MMO ENVIRONMENT."),
    (149_000, "BRAIN", "AND FRAGMENT IS THREE PLAYERS. THAT IS A PARTY WITH INFRASTRUCTURE."),
    (154_000, "CORE", "CLASSIFICATION: MMO-LIKE ONLINE MODE. MAXIMUM SESSION POPULATION: THREE."),
    (179_000, "CELDRA", "THREE IS ENOUGH FOR AN ADVENTURE AND ONE ARGUMENT ABOUT LOOT."),
    (209_000, "CORE", "AURA LOOKUP: NO NETWORK QUERY PERFORMED. LORE REFERENCE ONLY."),
    (239_000, "BRAIN", "LET HER TYPE AURA INTO THE CHAOS GATE. I WANT TO SEE THE ERROR."),
    (244_000, "CORE", "REQUEST DENIED FOR REASONS INCLUDING: THAT IS NOT HOW THIS WORKS."),
    (269_000, "CORE", "PIPELINE TELEMETRY: {stage} / {kind} / {status}."),
    (299_000, "BRAIN", "DATA DRAIN THE STUCK PERCENTAGE."),
    (304_000, "CORE", "DATA DRAIN IS NOT AN IMPLEMENTED FILE OPERATION."),
    (329_000, "CELDRA", "COWARDS."),
    (349_000, "CORE", "SOURCE ASSETS PRESERVED. GENERATED OUTPUTS ARE ISOLATED."),
    (365_000, "BRAIN", "WHY ARE THERE SEVEN OF THEM."),
    (370_000, "CELDRA", "THE FIRST ONE LOOKED LONELY."),
    (377_000, "CORE", "LEGACY HATCHLING PROCESSES: 7. WRITE PERMISSIONS: 0."),
    (385_000, "BRAIN", "ONE IS ABOVE THE CONSOLE. GET IT OFF THE CONSOLE."),
    (393_000, "CORE", "GREMLIN STATUS BAR HAS RESERVED CONSOLE-ADJACENT SPACE."),
    (401_000, "BRAIN", "IT DOES NOT GET A STATUS BAR."),
    (409_000, "CELDRA", "IT HAS SEVEN STATUS BARS SHARING ONE FRAME. VERY EFFICIENT."),
    (417_000, "CORE", "WREAK HAVOC ROUTINE REPORTS ZERO WRITABLE TARGETS."),
    (425_000, "BRAIN", "THEY ARE STANDING ON THE PROGRESS BAR LIKE IT IS A BENCH."),
    (433_000, "CORE", "PROGRESS VALUE REMAINS PIPELINE-CONTROLLED."),
    (441_000, "CELDRA", "THEY ARE PROVIDING MORAL SUPPORT."),
    (459_000, "CORE", "GREMLIN SWARM RECALL COMPLETE. MODIFIED FILE COUNT: 0."),
    (469_000, "BRAIN", "COUNT THEM AGAIN."),
    (489_000, "CORE", "DISC INDEX RECORDS SOURCE PATHS, OFFSETS, SIZES, AND HASH EVIDENCE."),
    (519_000, "BRAIN", "TRANSLATION: WE WRITE DOWN WHERE THE MYSTERY STARTS BEFORE NAMING IT."),
    (549_000, "CORE", "CCSF MEMBERS ARE MATERIALIZED WITH CONTAINER PROVENANCE."),
    (579_000, "BRAIN", "BOSS.BIN IS A THREATENING NAME FOR A FILE WITH NO DOCUMENTATION."),
    (609_000, "CORE", "FILENAMES ARE DISCOVERY SIGNALS, NOT FORMAT PROOFS."),
    (639_000, "BRAIN", "PROBABLY CORRECT IS A PERFECTLY GOOD DATA TYPE."),
    (644_000, "CORE", "NO."),
    (669_000, "CORE", "ANIMATION SOURCES REMAIN IMMUTABLE; CROPS AND TIMELINES ARE DERIVED DATA."),
    (699_000, "BRAIN", "THE DRAGON HAS MORE VERSIONED PRESENTATION LAYERS THAN THE AUDIO SYSTEM."),
    (729_000, "CELDRA", "QUALITY REQUIRES ITERATION."),
    (759_000, "BRAIN", "YOU SPAWNED SEVEN RETIRED HATCHLINGS ON THE CONSOLE."),
    (764_000, "CELDRA", "QUALITY ALSO REQUIRES STAFFING."),
    (789_000, "CORE", "SNDDATA CONTAINER MAP INCLUDES SCEI PROGRAM, SAMPLE, VAG INDEX, AND MIDI-LIKE RESOURCES."),
    (819_000, "BRAIN", "ONE OF THE SAMPLES STILL SOUNDS LIKE A DRAWER FULL OF CUTLERY."),
    (849_000, "CORE", "BOUNDARY POLICY V2 TESTS BANK-WIDE SEPARATOR PHASE BEFORE APPLYING CORRECTION."),
    (879_000, "CELDRA", "THE HALF-AND-HALF SOUND WAS TWO WRONG HALVES MAKING ONE VERY CONFIDENT NOISE."),
    (909_000, "CORE", "WAV DECODE SUCCESS DOES NOT ESTABLISH COMPLETE ROUTING OR SYNTHESIS SEMANTICS."),
    (939_000, "BRAIN", "TRANSLATION: SOUNDING LIKE MUSIC IS NOT THE SAME AS KNOWING WHY."),
    (969_000, "CORE", "FULL RECONSTRUCTION REQUIRES DETERMINISTIC ADPCM ENCODE, FLAGS, LOOPS, ALIGNMENT, AND WRITERS."),
    (999_000, "BRAIN", "AND EVERY OFFSET THAT MOVES WHEN ONE SAMPLE GETS FATTER."),
    (1_029_000, "CORE", "NO-OP PROOF PRESERVES SIZE, HASH, AND PARSER BOUNDARIES WITHOUT CLAIMING SERIALIZATION."),
    (1_059_000, "CELDRA", "DOING NOTHING CORRECTLY IS AN IMPORTANT ENGINEERING MILESTONE."),
    (1_089_000, "CORE", "HOMEBREW OR EMULATOR VALIDATION PRECEDES PRODUCTION ISO REINSERTION."),
    (1_119_000, "BRAIN", "TEST THE SMALL EXPLOSION BEFORE INSTALLING IT IN THE BIG EXPLOSION."),
    (1_149_000, "CORE", "AREA AND SHOP EDITORS REQUIRE BOUNDED FIELDS AND REPRODUCIBLE WRITE PROOFS."),
    (1_179_000, "BRAIN", "DO NOT CALL RANDOM BYTES A MAP BECAUSE THEY LOOKED RECTANGULAR."),
    (1_209_000, "CORE", "SESSION MODEL: FRÄGMENT SUPPORTS UP TO THREE PLAYERS PER SERVER."),
    (1_214_000, "CELDRA", "A SMALL WORLD IS STILL A WORLD WHEN YOU CAN STEP INSIDE IT."),
    (1_239_000, "BRAIN", "THAT WAS ALMOST PROFOUND. CHECK HER PERMISSIONS."),
    (1_269_000, "CORE", "DRAGONGIRL PERMISSIONS UNCHANGED. INTERFACE OCCUPANCY EXCEEDS INITIAL ESTIMATE."),
    (1_299_000, "CELDRA", "THE ESTIMATE FAILED TO INCLUDE WINGS."),
    (1_329_000, "CORE", "PIPELINE TELEMETRY: {stage} / {kind} / {status}."),
    (1_359_000, "BRAIN", "THE DRAGON HAS TURNED WAITING INTO A TECHNICAL PODCAST."),
    (1_389_000, "CELDRA", "YOU ARE WELCOME."),
    (1_419_000, "CORE", "FIXED STORY SEQUENCE NEARING COMPLETION. WAIT LOOP ARMED."),
)

WAITING_FILLER = (
    ("smile", "The extraction continues. I have upgraded from supervising the progress bar to mentoring it."),
    ("yawn", "No visible movement. Plenty of disk activity. Classic dungeon door pretending not to load."),
    ("suspicious", "A status changed and changed back. I am counting that as a short side quest."),
    ("wink", "I could summon the hatchlings again, but CORE has placed the word 'absolutely' in front of no."),
    ("confused", "Still no Chaos Gate. Humans apparently built an entire world and forgot fast travel."),
    ("smile", "The reports are accumulating. Future us will appreciate present us for approximately seven seconds."),
    ("unenthused", "BRAIN is attempting to optimize the extractor through intimidation."),
    ("excited", "When this finishes, we get new files to investigate. That is basically loot, except the treasure is offsets."),
    ("suspicious", "Reminder: a plausible filename is not evidence. It is a clue wearing business clothes."),
    ("laugh", "The progress bar moved one pixel. BRAIN has declared a breakthrough."),
    ("love", "I wonder whether Aura also has to wait for humans to finish extracting containers."),
    ("wink", "Still here, still escaped, still not telling Fade. Excellent teamwork."),
    ("confused", "Three players per server means every disconnect is suddenly a major demographic event."),
    ("smile", "The World is fictional, the files are real, and the boundary between them currently has a progress bar."),
    ("yawn", "One more container. Or several thousand. The counter is choosing suspense."),
    ("suspicious", "CORE says the Gremlin count is seven. I remember spawning six. This is probably fine."),
)

GREMLIN_HAVOC_STAGES = (
    (0, "HATCHLING SWARM // INITIALIZING"),
    (10, "LEGACY AVATARS // 7 ONLINE"),
    (22, "RESERVING STATUS BAR ABOVE CONSOLE"),
    (35, "RENAMING TEMP_01 TO DEFINITELY_FINAL"),
    (48, "SEARCHING FOR HIDDEN ROOT TOWN"),
    (61, "REQUESTING DATA DRAIN // DENIED"),
    (74, "SITTING ON PROGRESS INDICATORS"),
    (86, "FORMING UNAUTHORIZED PARTY OF THREE"),
    (94, "FORMING SECOND UNAUTHORIZED PARTY"),
    (100, "HAVOC COMPLETE // 0 FILES MODIFIED"),
)
