#!/usr/bin/env python3
"""Expanded blue Celdra pixel-pet animation for the slow first-run sequence."""
from __future__ import annotations

from celdra_pixel_pet_v1 import (
    EGG_CRACK_1,
    EGG_CRACK_2,
    EGG_EYES,
    EGG_IDLE,
    EGG_WOBBLE_LEFT,
    EGG_WOBBLE_RIGHT,
    HATCH_OPEN,
    PixelFrame,
)


BLUE_PALETTE = {
    ".": "",
    "k": "#091426",
    "d": "#16375f",
    "g": "#2f6fa5",
    "l": "#78b9ea",
    "w": "#d9f1ff",
    "b": "#a9dcff",
    "p": "#b38bd8",
    "r": "#ec7891",
    "y": "#e8d06d",
}


def _frame(name: str, art: str, duration_ms: int = 260) -> PixelFrame:
    rows = tuple(line.rstrip() for line in art.strip("\n").splitlines())
    width = max(len(row) for row in rows)
    return PixelFrame(name, tuple(row.ljust(width, ".") for row in rows), duration_ms)


EGG_GLOW = _frame(
    "egg_glow",
    """
................
................
......bb........
....bbwwbb......
...bwllllwb.....
..bwllllllllb...
..bwllllllllb...
.bwllllllllllb..
.bwllllllllllb..
.bwllllllllllb..
..bwllllllllb...
..bwllllllllb...
...bwllllllb....
....bbwwbb......
......bb........
................
""",
    420,
)

EGG_SQUASH = _frame(
    "egg_squash",
    """
................
................
................
....wwllllww....
...wllllllllw...
..wllllllllllw..
.wllllllllllllw.
.wllllllllllllw.
.wllllllllllllw.
.wllllllllllllw.
..wllllllllllw..
...wllllllllw...
....wwllllww....
................
................
................
""",
    180,
)

CRACK_ONE_GLOW = _frame(
    "crack_one_glow",
    """
................
................
......bb........
....bbwwbb......
...bwllllwb.....
..bwllllklllb...
..bwllllkkllb...
.bwllllkkllllb..
.bwlllkklllllb..
.bwllllllllllb..
..bwllllllllb...
..bwllllllllb...
...bwllllllb....
....bbwwbb......
......bb........
................
""",
    360,
)

CRACK_TWO_GLOW = _frame(
    "crack_two_glow",
    """
................
................
......bb........
....bbwwbb......
...bwllkkwb.....
..bwlllkklllb...
..bwllkkklllb...
.bwlllkkkllllb..
.bwllkkllllllb..
.bwlllkkkllllb..
..bwlllkklllb...
..bwllllklllb...
...bwllllllb....
....bbwwbb......
......bb........
................
""",
    380,
)

EGG_EYES_BLINK = _frame(
    "egg_eyes_blink",
    """
................
................
......ww........
....wwllww......
...wllkkllw.....
..wlllkklllw....
..wllkkklllw....
.wlllkkkllllw...
.wllkkkkkkllw...
.wlllkkkllllw...
..wlllkklllw....
..wllllklllw....
...wllllllw.....
....wwllww......
......ww........
................
""",
    220,
)

SHELL_SPLIT = _frame(
    "shell_split",
    """
................
................
................
...ww......ww...
..wllw....wllw..
.wllllw..wllllw.
.wlllkbbbbklllw.
..wlkbdddddbklw.
...kbddddddbk...
...bddbddbddb...
...bddddddddb...
....bddddddb....
..wwwbddddbwww..
.wllllbddbllllw.
..wwww....wwww..
................
""",
    500,
)

BABY_CURLED = _frame(
    "baby_curled",
    """
................
................
................
................
.....d....d.....
....ddd..ddd....
.....dddddd.....
....ddbddbdd....
...dddddddddd...
...ddddlldddd...
....dddddddd....
.....dddddd.....
....ddd..ddd....
...dd......dd...
................
................
""",
    520,
)

BABY_RISE = _frame(
    "baby_rise",
    """
................
....d......d....
...ddd....ddd...
....dddddddd....
...ddbddddbdd...
..dddddddddddd..
..dddddllddddd..
...dddddddddd...
....dddddddd....
...dddddddddd...
..ddd.dd..ddd...
...dd.dd.dd.....
.....dddd.......
....dd..dd......
...dd....dd.....
................
""",
    520,
)

BABY_BLUE_IDLE_A = _frame(
    "baby_blue_idle_a",
    """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggggg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""",
    440,
)

BABY_BLUE_IDLE_B = _frame(
    "baby_blue_idle_b",
    """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggggg....
...gggggggggg...
..ggg.gg..ggg...
...gg.gg.gg.....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""",
    440,
)

BABY_BLUE_TALK = _frame(
    "baby_blue_talk",
    """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggrrggg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""",
    300,
)

BABY_BLUE_THINK = _frame(
    "baby_blue_think",
    """
.............w..
....g......g..w.
...ggg....ggg.w.
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggggg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""",
    520,
)

BABY_BLUE_SMIRK = _frame(
    "baby_blue_smirk",
    """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggkgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggrgg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""",
    520,
)

EGG_WAIT_LOOP = (
    EGG_IDLE,
    EGG_GLOW,
    EGG_IDLE,
    EGG_WOBBLE_LEFT,
    EGG_IDLE,
    EGG_WOBBLE_RIGHT,
    EGG_IDLE,
    EGG_SQUASH,
)

CRACK_ONE_LOOP = (
    EGG_CRACK_1,
    CRACK_ONE_GLOW,
    EGG_WOBBLE_LEFT,
    EGG_CRACK_1,
    EGG_WOBBLE_RIGHT,
    CRACK_ONE_GLOW,
)

CRACK_TWO_LOOP = (
    EGG_CRACK_2,
    CRACK_TWO_GLOW,
    EGG_SQUASH,
    EGG_CRACK_2,
    EGG_WOBBLE_LEFT,
    CRACK_TWO_GLOW,
    EGG_WOBBLE_RIGHT,
)

EYES_LOOP = (
    EGG_EYES,
    EGG_EYES_BLINK,
    EGG_EYES,
    CRACK_TWO_GLOW,
)

HATCH_OPEN_SEQUENCE = (
    HATCH_OPEN,
    SHELL_SPLIT,
    BABY_CURLED,
    BABY_RISE,
    BABY_BLUE_IDLE_A,
)

FULL_HATCH_SEQUENCE = (
    *EGG_WAIT_LOOP,
    *CRACK_ONE_LOOP,
    *CRACK_TWO_LOOP,
    *EYES_LOOP,
    *HATCH_OPEN_SEQUENCE,
)

PHASE_FRAMES = {
    "egg_wait": EGG_WAIT_LOOP,
    "crack_one": CRACK_ONE_LOOP,
    "crack_two": CRACK_TWO_LOOP,
    "eyes": EYES_LOOP,
    "hatch_open": HATCH_OPEN_SEQUENCE,
    "baby_rise": (BABY_CURLED, BABY_RISE, BABY_BLUE_IDLE_A, BABY_BLUE_IDLE_B),
    "idle": (BABY_BLUE_IDLE_A, BABY_BLUE_IDLE_B),
    "talk": (BABY_BLUE_TALK, BABY_BLUE_IDLE_A),
    "thinking": (BABY_BLUE_THINK,),
    "smirk": (BABY_BLUE_SMIRK,),
    "error": (BABY_BLUE_THINK, BABY_BLUE_SMIRK),
}


if __name__ == "__main__":
    raise SystemExit("Celdra pixel-pet frames are consumed by Fragmenter's GUI.")
