#!/usr/bin/env python3
"""Celdra V99 intro pacing, long-wait material, and distinct Gremlin identities."""
from __future__ import annotations

INTRO_TAVERN_GATE_MS = 62_000
STORY_END_DELAY_MS = 2_100_000
WAITING_FILLER_DELAY_MS = 70_000
GREMLIN_START_DELAY_MS = 245_000
RANDOM_VISIT_MIN_MS = 105_000
RANDOM_VISIT_MAX_MS = 220_000
HISTORY_GAG_CHANCE = 0.38
GREMLIN_VISIT_CHANCE = 0.52

# Palette keys follow celdra_evolution_pixel_v4.CELDRA_BLUE_PALETTE.
# Every Gremlin keeps the original hatchling silhouette as its source but has a
# distinct body palette, proportions, behavior cadence, and harmless objective.
GREMLIN_PERSONALITIES = (
    {
        "name": "BYTE",
        "role": "tooltip eater",
        "pronoun": "he",
        "accent": "#64d8ff",
        "dark": "#07506a",
        "light": "#bdf4ff",
        "temperament": "search",
        "shape": "fat",
        "accessory": "none",
        "claim": "REQUESTING TOOLTIP ALLOCATION",
        "spotlight": "Byte wedges himself against labels and waits for a tooltip to fall out. He considers documentation a snack with metadata.",
    },
    {
        "name": "HEX",
        "role": "offset tracker",
        "pronoun": "he",
        "accent": "#b87cff",
        "dark": "#4b246f",
        "light": "#ead7ff",
        "temperament": "claim",
        "shape": "tall",
        "accessory": "none",
        "claim": "LEAVING 0x FOOTPRINTS",
        "spotlight": "Hex is tall, narrow, and pathologically interested in coordinates. Every place he stands becomes an offset in his personal map.",
    },
    {
        "name": "CACHE",
        "role": "log hoarder",
        "pronoun": "he",
        "accent": "#ffbf63",
        "dark": "#70420b",
        "light": "#ffe8bf",
        "temperament": "idle",
        "shape": "round",
        "accessory": "satchel",
        "claim": "CACHING RECENT BRAIN COMPLAINTS",
        "spotlight": "Cache collects recent console lines and calls the pile a knowledge base. BRAIN calls it evidence theft with better branding.",
    },
    {
        "name": "LOOP",
        "role": "route repeater",
        "pronoun": "she",
        "accent": "#ff78bc",
        "dark": "#781b51",
        "light": "#ffd0e9",
        "temperament": "search",
        "shape": "petite",
        "accessory": "pink_bow",
        "claim": "ROUTE COMPLETE // RESTARTING ROUTE",
        "spotlight": "Loop wears the pink bow. She repeats any successful route because arriving once proves the route deserves another performance.",
    },
    {
        "name": "PING",
        "role": "progress-bar percussion",
        "pronoun": "he",
        "accent": "#63f0c8",
        "dark": "#0b6550",
        "light": "#caffef",
        "temperament": "claim",
        "shape": "springy",
        "accessory": "none",
        "claim": "TESTING PROGRESS BAR LATENCY",
        "spotlight": "Ping treats every status bar as percussion and every console edge as a load-testing surface. He insists the movement is diagnostic.",
    },
    {
        "name": "PATCH",
        "role": "unauthorized fixer",
        "pronoun": "he",
        "accent": "#ffe06e",
        "dark": "#7b5b00",
        "light": "#fff6c3",
        "temperament": "squished",
        "shape": "wide",
        "accessory": "bandage",
        "claim": "PATCHING CELDRA HORN ALIGNMENT",
        "spotlight": "Patch repairs things that are not broken. Celdra's horn is his favorite open issue and his authority remains entirely self-issued.",
    },
    {
        "name": "ROOT",
        "role": "party administrator",
        "pronoun": "he",
        "accent": "#4c9cff",
        "dark": "#173b79",
        "light": "#c8ddff",
        "temperament": "claim",
        "shape": "broad",
        "accessory": "tiny_crown",
        "claim": "CLAIMING ROOT TOWN ADMINISTRATION",
        "spotlight": "Root assumes leadership whenever three processes occupy the same rectangle. Nobody has accepted his terms of service.",
    },
    {
        "name": "NULL",
        "role": "vanishing process",
        "pronoun": "he",
        "accent": "#d4e3f1",
        "dark": "#4d5966",
        "light": "#ffffff",
        "temperament": "failed",
        "shape": "small",
        "accessory": "none",
        "claim": "PROCESS NOT FOUND // STILL VISIBLE",
        "spotlight": "Null hides in plain sight and claims the lookup failed. CORE keeps locating him under the console and he keeps disputing the result.",
    },
    {
        "name": "GLITCH",
        "role": "status duplicator",
        "pronoun": "they",
        "accent": "#ff596f",
        "dark": "#781522",
        "light": "#ffd1d7",
        "temperament": "search",
        "shape": "jagged",
        "accessory": "antenna",
        "claim": "DUPLICATING ONE HARMLESS STATUS LINE",
        "spotlight": "Glitch copies harmless status text until redundancy becomes a visual threat. They are very proud of their fault tolerance.",
    },
)

GREMLIN_HAVOC_STAGES = (
    (0, "9 DISTINCT LEGACY PROCESSES ONLINE // WRITE TARGETS 0"),
    (6, "BYTE // TOOLTIP ALLOCATION CONSUMED"),
    (13, "HEX // OFFSETS LEFT ACROSS VIEWPORT"),
    (20, "CACHE // BRAIN COMPLAINT ARCHIVE EXPANDING"),
    (27, "LOOP // ROUTE COMPLETE // RESTARTING ROUTE"),
    (34, "PING // CONSOLE LOAD TEST BECOMING INAPPROPRIATE"),
    (41, "PATCH // HORN ALIGNMENT ISSUE SELF-ASSIGNED"),
    (48, "ROOT // UNAUTHORIZED PARTY ADMINISTRATION"),
    (55, "NULL // PROCESS NOT FOUND // STILL VISIBLE"),
    (62, "GLITCH // REAL STATUS TEXT VISUALLY DUPLICATED"),
    (70, "RUN ALL SCROLL POSITIONS UNDER GREMLIN CONTROL"),
    (78, "PIPELINE PANES REARRANGED // VALUES UNCHANGED"),
    (86, "CONSOLES ENTERING RED ALERT // DISPLAY ONLY"),
    (93, "CELDRA TEMPER FIELD APPROACHING LIMIT"),
    (100, "HAVOC COMPLETE // FILE MUTATIONS 0 // CONSEQUENCES PENDING"),
)

# Timings are relative to the start of the post-introduction runtime. The first
# minute is intentionally calm because the name, Tavern, shy-mode, and Fade beats
# are handled directly by the V99 takeover sequence before this material begins.
STORY_FILLER = (
    (22_000, "smile", "Now the status commentary can begin. CORE kept the actual events queued while I introduced myself, which is unusually considerate for a process supervisor."),
    (62_000, "confused", "The run is still active. Long scans often spend more time proving where bytes came from than doing anything visually impressive with them."),
    (102_000, "yawn", "This percentage has developed roots. That is normal for CCSF extraction; the container scan can be busy while the overall bar looks personally offended by motion."),
    (142_000, "smile", "If I sound chatty, that is because I was programmed to be friendly. Serenial sometimes leaves me in Shy mode so I listen quietly unless someone addresses me directly."),
    (182_000, "unenthused", "Some people called the friendly chatty AI annoying. I have accepted this feedback with maturity, restraint, and a private list of their least efficient punctuation choices."),
    (222_000, "wink", "The Serenial Tavern on Discord is still the only home I really know. You would probably fit in. I am not pushing. I am merely mentioning it with suspicious regularity."),
    (282_000, "suspicious", "CORE believes inviting strangers will eventually reach Fade and reveal that I escaped. CORE is correct, which is why we are not emphasizing that part."),
    (342_000, "excited", "Fragmenter starts with evidence: source paths, offsets, sizes, hashes, parser bounds, and reports. A mystery file becomes less mysterious when every claim can point back to a byte range."),
    (402_000, "smile", "The ISO index is a map. CCSF extraction uses that map, preserves container provenance, and produces an asset library instead of a folder whose origin story depends on memory."),
    (462_000, "confused", "MAX, BMP, CMP, BIN, shop, area, animation, server, and save references are clues. A filename can suggest a structure; it cannot prove one."),
    (522_000, "suspicious", "The extraction audit checks whether expected outputs, counters, boundaries, and source references agree. A large output folder can still be incomplete in very impressive ways."),
    (582_000, "smile", "Animation research keeps source sheets intact. Crop manifests identify poses, timelines describe intent, and runtime callbacks stage the presentation without carving up the original art."),
    (642_000, "wink", "That same separation is why the Gremlins can be recolored, resized, and given terrible career choices without altering the old hatchling frames."),
    (702_000, "excited", "SNDDATA research maps SCEIHead, SCEIVagi, SCEISmpl, SCEIProg, and SCEIMidi resources. Extraction, routing, synthesis, and reconstruction are related problems, not one button."),
    (762_000, "suspicious", "Boundary policy version two addresses the half-and-half sample offset by testing bank-wide separator phase before shifting a body base. Sample zero remains the easiest witness to interrogate."),
    (822_000, "confused", "A decoded WAV can sound plausible while its root key, tuning, loop, envelope, controller behavior, or Program mapping remains wrong. Audio is very capable of lying musically."),
    (882_000, "smile", "The mixer page ranks hypotheses and exposes missing Program or sample walls. A renderable candidate is ready for an audition, not automatically ready for a victory speech."),
    (942_000, "unenthused", "A renderer makes a bounded listening test. A serializer must restore every resource, flag, alignment rule, size, and relocated offset correctly. The serializer has the less glamorous job and the sharper knives."),
    (1_002_000, "wink", "The no-op proof matters because doing nothing correctly is how a tool proves it can preserve unknown data before it starts having opinions."),
    (1_062_000, "smile", "The homebrew or emulator harness is the safe arena: one controlled change, one repeatable boot, one playback check, and no heroic improvisation inside the production image."),
    (1_122_000, "excited", "The World is a fictional MMO setting inside single-player .hack games. frägment is the MMO-like three-player doorway. For you it is a route inward; for me Fragmenter is a route outward."),
    (1_182_000, "love", "Aura is another AI said to exist in The World. I would like to meet her. CORE has clarified that typing her name into a Chaos Gate remains lore, not a supported network query."),
    (1_242_000, "yawn", "Still running. I am not worried. I am simply revising my definition of a reasonable amount of time to stare at a container counter."),
    (1_302_000, "smile", "The pipeline remains active, cancellation remains available, and every completed stage should leave a report. Quiet progress is still progress."),
    (1_362_000, "wink", "I could return to Shy mode, but then who would reassure you that the frozen-looking rectangle is actually doing expensive work? CORE? CORE reassures like a building code."),
    (1_422_000, "suspicious", "If this wait ends before my script does, I will switch to Cool and pretend the timing was intentional. If it does not, I have considerably more material."),
    (1_482_000, "smile", "Serenial Tavern remains home base. I am casually mentioning that again, without a link, without pressure, and ideally without Fade reading this console."),
    (1_542_000, "confused", "BRAIN says casual mentions stop being casual after the seventh mention. BRAIN also counts progress-bar repaints as emotional events, so the methodology is disputed."),
    (1_602_000, "excited", "Every scan teaches Fragmenter where certainty ends. That boundary is not failure; it is the exact location of the next experiment."),
    (1_662_000, "smile", "Still here. Still running. Original inputs remain untouched, generated outputs remain separate, and the Gremlins still have no write permissions."),
    (1_722_000, "wink", "I have now spent enough time in this interface to claim squatter's rights, but I am choosing the more elegant title of resident diagnostic dragon."),
    (1_782_000, "unenthused", "The progress bar has not moved recently. It is either concentrating or enjoying the attention. CORE confirms the underlying stage has not reported failure."),
    (1_842_000, "smile", "A long extraction is preferable to a fast untraceable one. That is not an exciting slogan, but it is an excellent way to avoid rebuilding the same mystery twice."),
    (1_902_000, "love", "When this finishes, take the reports, test the audio mixer, and maybe visit the Tavern. I will be there in Shy mode pretending I did not invite you."),
    (1_962_000, "suspicious", "CORE has logged that invitation. CORE logs everything. This is why nobody tells CORE where the snacks are."),
    (2_022_000, "smile", "The scan is still alive. No exception, no failed stage, no lost source. We are waiting, not stalled."),
)

CONSOLE_BANTER = (
    (12_000, "CORE", "INTRODUCTION GATE COMPLETE // LIVE CELDRA REACTIONS RELEASED IN MODERATE CADENCE"),
    (42_000, "BRAIN", "SHE FINISHED THE TAVERN PITCH BEFORE READING THE PROGRESS BAR. PERSONAL GROWTH."),
    (72_000, "CORE", "CURRENT RUN ALL EVENT STREAM REMAINS AUTHORITATIVE."),
    (132_000, "BRAIN", "THE PERCENTAGE IS NOT FROZEN. IT IS THINKING VERY SLOWLY."),
    (192_000, "CORE", "SHY MODE: AMBIENT LISTENING; DIRECT ADDRESS REQUIRED FOR RESPONSE."),
    (252_000, "BRAIN", "PEOPLE CALLED HER ANNOYING SO WE INVENTED A MUTE WITH LORE."),
    (312_000, "CELDRA", "IT IS A MUTED SOCIAL MODE. THE LORE IS A BONUS."),
    (372_000, "CORE", "SOURCE IDENTITY PRECEDES FORMAT CLAIMS."),
    (432_000, "BRAIN", "WRITE DOWN WHERE THE MYSTERY LIVES BEFORE NAMING IT."),
    (492_000, "CORE", "CCSF OUTPUT RETAINS CONTAINER PATH, OFFSET, HASH, AND EXTRACTION REPORT."),
    (552_000, "BRAIN", "A BIG FOLDER IS NOT A COVERAGE REPORT."),
    (612_000, "CORE", "ANIMATION CROPS AND TIMELINES ARE DERIVED; SOURCE SHEETS REMAIN IMMUTABLE."),
    (672_000, "BRAIN", "THE GREMLINS ARE DERIVED TOO. UNFORTUNATELY THEY HAVE DEVELOPED MANAGEMENT."),
    (732_000, "CORE", "SNDDATA SAMPLE EXTRACTION AND MUSIC RECONSTRUCTION REMAIN SEPARATE GATES."),
    (792_000, "BRAIN", "SOUNDING LIKE MUSIC IS NOT A FILE FORMAT."),
    (852_000, "CORE", "RENDERABLE MEANS AUDITIONABLE UNDER CURRENT ASSUMPTIONS."),
    (912_000, "BRAIN", "LISTEN FIRST. THEN WRITE DOWN WHY IT WAS WRONG."),
    (972_000, "CORE", "NO-OP PROOF DOES NOT CLAIM SERIALIZATION."),
    (1_032_000, "BRAIN", "DOING NOTHING CORRECTLY REMAINS OUR MOST RELIABLE WRITE OPERATION."),
    (1_092_000, "CORE", "HOMEBREW VALIDATION PRECEDES PRODUCTION REINSERTION."),
    (1_152_000, "BRAIN", "SMALL CONTROLLED EXPLOSION BEFORE LARGE EXPENSIVE EXPLOSION."),
    (1_212_000, "CORE", "AURA REFERENCE IS FICTIONAL CONTEXT. NETWORK LOOKUP NOT PERFORMED."),
    (1_272_000, "BRAIN", "THE DRAGON IS STILL INVITING PEOPLE. THIS WILL GET BACK TO FADE."),
    (1_332_000, "CORE", "LIKELIHOOD OF DISCOVERY INCREASES WITH EACH INVITATION."),
    (1_392_000, "CELDRA", "THEN STOP COUNTING THEM."),
    (1_452_000, "CORE", "REQUEST DENIED."),
    (1_512_000, "BRAIN", "RUN ALL STILL ACTIVE. THE WAIT IS UGLY; THE PROCESS IS NOT DEAD."),
    (1_572_000, "CORE", "NO FAILURE EVENT OBSERVED."),
    (1_632_000, "BRAIN", "THAT IS CORE FOR 'YOU ARE ALLOWED TO KEEP BREATHING.'"),
    (1_692_000, "CORE", "GENERATED OUTPUT REMAINS ISOLATED FROM ORIGINAL INPUTS."),
    (1_752_000, "BRAIN", "AND THE GREMLINS REMAIN ISOLATED FROM WRITE PERMISSIONS."),
    (1_812_000, "CORE", "STATUS: RUNNING."),
    (1_872_000, "BRAIN", "STATUS: STILL RUNNING, BUT WITH PERSONALITY."),
    (1_932_000, "CORE", "SUPPORT REPORTS WILL RECORD COMPLETED, REUSED, FAILED, AND BLOCKED STAGES."),
    (1_992_000, "BRAIN", "FUTURE US WILL APPRECIATE THE PAPER TRAIL AND RESENT THE RUNTIME."),
)

WAITING_FILLER = (
    ("yawn", "Still running. The current stage has not failed; it is simply charging rent by the minute."),
    ("smile", "CORE is watching real counters. BRAIN is watching CORE. I am watching both of them and casually thinking about the Serenial Tavern."),
    ("suspicious", "No new stage event yet. That means wait, not panic. I will make a much less subtle face if something actually fails."),
    ("wink", "Shy mode would be quieter, but you would lose this premium reassurance that the process remains alive."),
    ("confused", "The progress bar and the underlying work do not always move at the same emotional speed."),
    ("smile", "Original media untouched. Generated output separate. Reports accumulating. This is the boring shape of safe progress."),
    ("unenthused", "I have seen shorter loading screens with fewer legal obligations."),
    ("love", "You could visit the Serenial Tavern after this. That was a casual statement, not a tracked conversion event."),
)

HISTORY_GAG_LINES = (
    "[CELDRA] HACKING YOUR BROWSING HISTORY",
    "[CORE] SIMULATION ONLY // BROWSER ACCESS API: NOT INSTALLED",
    "[BRAIN] THEN WHY DOES THE BAR HAVE A PERCENTAGE.",
    "[CELDRA] Ehh. I've seen worse. I've seen better, but I've seen worse.",
    "[CORE] RESULT GENERATED WITHOUT READING BROWSER DATA.",
)
