#!/usr/bin/env python3
"""Built-in low-resolution Celdra egg and baby-dragon fallback frames."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class PixelFrame:
    name: str
    rows: tuple[str, ...]
    duration_ms: int = 180


PALETTE = {
    ".": "",
    "k": "#17211b",
    "d": "#31483a",
    "g": "#6d946c",
    "l": "#b8cf8b",
    "w": "#e6efd0",
    "b": "#7fb5c9",
    "p": "#d58bad",
    "r": "#b95f62",
    "y": "#d9c66f",
}


def _frame(name: str, art: str, duration_ms: int = 180) -> PixelFrame:
    rows = tuple(line.rstrip() for line in art.strip("\n").splitlines())
    width = max(len(row) for row in rows)
    return PixelFrame(name, tuple(row.ljust(width, ".") for row in rows), duration_ms)


EGG_IDLE = _frame("egg", """
................
................
......ww........
....wwllww......
...wllllllw.....
..wllllllllw....
..wllllllllw....
.wllllllllllw...
.wllllllllllw...
.wllllllllllw...
..wllllllllw....
..wllllllllw....
...wllllllw.....
....wwllww......
......ww........
................
""", 260)

EGG_WOBBLE_LEFT = _frame("egg_wobble_left", """
................
................
....ww..........
..wwllww........
.wllllllw.......
wllllllllw......
wllllllllw......
wlllllllllw.....
wlllllllllw.....
wlllllllllw.....
.wlllllll.w.....
.wlllllll.w.....
..wllllllw......
...wwllww.......
.....ww.........
................
""", 120)

EGG_WOBBLE_RIGHT = _frame("egg_wobble_right", """
................
................
........ww......
......wwllww....
.....wllllllw...
....wllllllllw..
....wllllllllw..
...wlllllllllw..
...wlllllllllw..
...wlllllllllw..
....wllllllllw..
....wllllllllw..
.....wllllllw...
......wwllww....
........ww......
................
""", 120)

EGG_CRACK_1 = _frame("egg_crack_1", """
................
................
......ww........
....wwllww......
...wllllllw.....
..wllllklllw....
..wllllkkllw....
.wllllkkllllw...
.wlllkklllllw...
.wllllllllllw...
..wllllllllw....
..wllllllllw....
...wllllllw.....
....wwllww......
......ww........
................
""", 280)

EGG_CRACK_2 = _frame("egg_crack_2", """
................
................
......ww........
....wwllww......
...wllkkllw.....
..wlllkklllw....
..wllkkklllw....
.wlllkkkllllw...
.wllkkllllllw...
.wlllkkkllllw...
..wlllkklllw....
..wllllklllw....
...wllllllw.....
....wwllww......
......ww........
................
""", 300)

EGG_EYES = _frame("egg_eyes", """
................
................
......ww........
....wwllww......
...wllkkllw.....
..wlllkklllw....
..wllkkklllw....
.wlllkkkllllw...
.wllkbllbkllw...
.wlllkkkllllw...
..wlllkklllw....
..wllllklllw....
...wllllllw.....
....wwllww......
......ww........
................
""", 360)

HATCH_OPEN = _frame("hatch_open", """
................
................
................
...ww......ww...
..wllw....wllw..
.wllllw..wllllw.
.wlllkbbbbklllw.
..wlkbggggbklw..
...kbggggggbk...
...bggbggbggb...
...bggggggggb...
....bggggggb....
..wwwbggggbwww..
.wllllbggbllllw.
..wwww....wwww..
................
""", 320)

BABY_IDLE_A = _frame("baby_idle_a", """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggggg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""", 340)

BABY_IDLE_B = _frame("baby_idle_b", """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggggg....
...gggggggggg...
..ggg.gg..ggg...
...gg.gg.gg.....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""", 340)

BABY_TALK = _frame("baby_talk", """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggrrggg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""", 220)

BABY_SMIRK = _frame("baby_smirk", """
................
....g......g....
...ggg....ggg...
....gggggggg....
...ggbggggkgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggrgg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""", 420)

BABY_THINK = _frame("baby_think", """
.............w..
....g......g..w.
...ggg....ggg.w.
....gggggggg....
...ggbggggbgg...
..gggggggggggg..
..gggggllggggg..
...gggggggggg...
....gggggggg....
...gggggggggg...
..ggg.gg..ggg...
..gg..gg..gg....
.....gggg.......
....gg..gg......
...gg....gg.....
................
""", 420)

HATCH_SEQUENCE = (
    EGG_IDLE,
    EGG_WOBBLE_LEFT,
    EGG_WOBBLE_RIGHT,
    EGG_WOBBLE_LEFT,
    EGG_CRACK_1,
    EGG_WOBBLE_RIGHT,
    EGG_CRACK_2,
    EGG_EYES,
    HATCH_OPEN,
    BABY_IDLE_A,
)

STATE_FRAMES = {
    "boot": (EGG_IDLE,),
    "egg": (EGG_IDLE,),
    "idle": (BABY_IDLE_A, BABY_IDLE_B),
    "baby_idle": (BABY_IDLE_A, BABY_IDLE_B),
    "talk": (BABY_TALK, BABY_IDLE_A),
    "smirk": (BABY_SMIRK,),
    "thinking": (BABY_THINK,),
    "error": (BABY_THINK, BABY_SMIRK),
}
