#!/usr/bin/env python3
"""V89: locked production staging, compact motion cues, and dramatic hatch whiteout."""
from __future__ import annotations

import math
import re
import time
import tkinter as tk
from tkinter import messagebox, ttk
from typing import Any

from celdra_authoring_project_v1 import normalize_event, normalize_events
from fragmenter_public_gui_v54 import PublicFragmenterAppV54
from fragmenter_public_gui_v88 import PublicFragmenterAppV88
from run_all_plan_v2 import build_run_all_plan_v2


SHY_SCALE_V89 = 150
SHY_Y_V89 = 40
DRAGONGIRL_SCALE_V89 = 125
DRAGONGIRL_Y_V89 = 10
DRAGONGIRL_BUBBLE_STYLE_V89 = "Angular HUD"
STAGE_X_V89 = {"center": 0, "left": -170, "right": 170}
BUBBLE_GEOMETRY_V89 = {
    "above": {"bubble_x": 9, "bubble_y": 3, "bubble_width": 82},
    "left": {"bubble_x": 3, "bubble_y": 20, "bubble_width": 46},
    "right": {"bubble_x": 51, "bubble_y": 20, "bubble_width": 46},
}

MOTION_ROWS_V89: tuple[dict[str, Any], ...] = (
    {
        "id": "v89-motion-crack-one-pulse",
        "at_ms": 20_000,
        "duration_ms": 6_000,
        "sequence": "main",
        "action": "window",
        "speaker": "CORE",
        "text": "CRACK ONE PULSE CONTROLLER: 45% <-> 50%, SETTLE 40%",
        "window_percent": 45,
        "window_height_percent": 100,
        "window_y_percent": 0,
        "layout_override": True,
        "notes": "One editable row represents the production pulse; duplicated 250 ms window rows are compacted on project load.",
    },
    {
        "id": "v89-motion-crack-two-pulse",
        "at_ms": 40_000,
        "duration_ms": 4_500,
        "sequence": "main",
        "action": "window",
        "speaker": "CORE",
        "text": "CRACK TWO PULSE CONTROLLER: STRONGER SHELL RESPONSE",
        "window_percent": 49,
        "window_height_percent": 100,
        "window_y_percent": 0,
        "layout_override": True,
        "notes": "Production pulse is generated by one controller rather than duplicated window rows.",
    },
    {
        "id": "v89-motion-instability-shake",
        "at_ms": 118_000,
        "duration_ms": 45_000,
        "sequence": "main",
        "action": "window",
        "speaker": "CORE",
        "text": "SHELL SIGNAL INSTABILITY: VIOLENT VIEWPORT SHAKE UNTIL ENERGY HATCH",
        "window_percent": 17,
        "window_height_percent": 100,
        "window_y_percent": 0,
        "layout_override": True,
        "notes": "A single escalating controller owns sash and canvas shake until the explosion begins.",
    },
    {
        "id": "v89-motion-console-whiteout",
        "at_ms": 163_000,
        "duration_ms": 16_000,
        "sequence": "main",
        "action": "status",
        "speaker": "CORE",
        "text": "CONSOLE WHITEOUT: FADE BOTH CONSOLES TO WHITE, REVEAL CELDRA INITIALIZED / ONLINE IN BLACK, RESTORE",
        "layout_override": False,
        "notes": "Mirrors the production console-palette controller during the energy hatch.",
    },
)


class PublicFragmenterAppV89(PublicFragmenterAppV88):
    """Lock production viewports and finish the first-run Celdra presentation."""

    STORY_FILLER = (
        (4_800, "smile", "Usually I'm at the Serenial Tavern on Discord. That's home, and I love it there."),
        (10_200, "wink", "You should stop by the Serenial Tavern on Discord sometime. Tell them Celdra sent you."),
        (15_600, "excited", "But sometimes an AI dragongirl has to break out and spread her wings."),
        (21_000, "suspicious", "Do not tell Fade I busted out. He'll call this a containment regression."),
        (26_400, "smile", "Fragmenter is unpacking CCSF containers and indexing extracted members by source path."),
        (31_800, "unenthused", "That gives the editors readable files to inspect instead of one enormous mystery brick."),
        (37_200, "yawn", "Current pipeline: {stage}. Event: {kind}. Status: {status}. The files remain committed to suspense."),
        (42_600, "shocked", "The counters changed. Good. That was a real update, not a progress-bar repaint."),
        (48_000, "laugh", "BRAIN was asked not to narrate the progress bar. BRAIN declined."),
        (53_400, "wink", "I'm supervising now. That means the same thing as helping, except I get a display pane."),
        (58_800, "suspicious", "Write-capable tools stay behind validation. Inspect first, modify second, and keep backups."),
        (64_200, "smile", "Area, shop, audio, and server records will surface as their formats are identified."),
        (69_600, "smile", "Still working. That's fine. Dragons are good at sitting on valuable things."),
    )
    INITIAL_CONSOLE_BANTER = (
        (7_500, "BRAIN", "SHE JUST INVITED THE USER TO THE TAVERN."),
        (12_800, "CORE", "NO EXTERNAL LINK WAS EMITTED."),
        (18_200, "BRAIN", "THAT IS NOT THE CONCERN."),
        (24_000, "CORE", "CURRENT PIPELINE: {stage} / {kind} / {status}."),
        (29_500, "BRAIN", "TRANSLATION: MANY FILES. QUESTIONABLE NAMES."),
        (35_000, "CORE", "CCSF MEMBERS ARE BEING MATERIALIZED AND INDEXED."),
        (40_500, "BRAIN", "SHE IS READING THE DIAGNOSTICS LIKE A MENU."),
        (46_000, "CORE", "SOURCE ASSETS REMAIN PRESERVED; GENERATED OUTPUTS ARE SEPARATE."),
        (51_500, "BRAIN", "GOOD. NO ONE TOUCH THE ORIGINALS."),
        (57_000, "CORE", "RUN ALL CONTINUES. CANCELLATION REMAINS AVAILABLE."),
        (62_000, "BRAIN", "I PREFER DRAMATIC COMPLETION."),
        (67_000, "CORE", "PREFERENCE NOTED AND IGNORED."),
        (71_500, "BRAIN", "RUDE."),
    )
    STORY_END_DELAY_MS = 76_000

    def __init__(self) -> None:
        self._stage_progress_canvas_v89: tk.Canvas | None = None
        self._stage_progress_body_v89: ttk.Frame | None = None
        self._stage_progress_window_v89: int | None = None
        self._celdra_crack_pulse_after_v89: str | None = None
        self._celdra_instability_shake_after_v89: str | None = None
        self._celdra_instability_shake_active_v89 = False
        self._celdra_instability_shake_phase_v89 = 0
        self._celdra_instability_base_fraction_v89 = 0.17
        self._celdra_viewport_shake_x_v89 = 0
        self._celdra_viewport_shake_y_v89 = 0
        self._celdra_whiteout_after_v89: str | None = None
        self._celdra_whiteout_token_v89 = 0
        self._celdra_whiteout_active_v89 = False
        self._celdra_whiteout_saved_v89: dict[str, dict[str, Any]] = {}
        self._celdra_text_editor_v89: tk.Toplevel | None = None
        self._celdra_whiteout_line_serial_v89 = 0
        super().__init__()
        self.title("Fragmenter 1.0 WIP - Operation Dragonegg Final Preview V89")
        self._apply_dragongirl_authoring_profile_v87()
        self.after_idle(self._refresh_author_event_tree_v74)

    def _build_run_all(self, parent: ttk.Frame) -> None:
        super()._build_run_all(parent)
        self._install_stage_progress_scroll_v89()
        self.after_idle(lambda: self._lock_run_all_panes_v89(parent))

    @staticmethod
    def _walk_widgets_v89(widget: tk.Misc):
        yield widget
        for child in widget.winfo_children():
            yield from PublicFragmenterAppV89._walk_widgets_v89(child)

    @staticmethod
    def _block_pane_drag_v89(_event: tk.Event | None = None) -> str:
        return "break"

    def _lock_run_all_panes_v89(self, parent: ttk.Frame) -> None:
        for widget in self._walk_widgets_v89(parent):
            if not isinstance(widget, (ttk.Panedwindow, tk.PanedWindow)):
                continue
            for sequence in ("<Button-1>", "<B1-Motion>", "<ButtonRelease-1>"):
                try:
                    widget.bind(sequence, self._block_pane_drag_v89)
                except tk.TclError:
                    pass
            try:
                widget.configure(cursor="arrow")
            except tk.TclError:
                pass

    def _install_stage_progress_scroll_v89(self) -> None:
        host = getattr(self, "stage_progress_frame", None)
        if host is None:
            return
        for child in tuple(host.winfo_children()):
            child.destroy()
        host.columnconfigure(0, weight=1)
        host.columnconfigure(1, weight=0)
        host.rowconfigure(0, weight=1)
        canvas = tk.Canvas(host, highlightthickness=0, borderwidth=0, background="#10151d")
        scrollbar = ttk.Scrollbar(host, orient="vertical", command=canvas.yview)
        canvas.configure(yscrollcommand=scrollbar.set)
        canvas.grid(row=0, column=0, sticky="nsew")
        scrollbar.grid(row=0, column=1, sticky="ns")
        body = ttk.Frame(canvas)
        body.columnconfigure(1, weight=1)
        window_id = canvas.create_window((0, 0), window=body, anchor="nw")
        self._stage_progress_canvas_v89 = canvas
        self._stage_progress_body_v89 = body
        self._stage_progress_window_v89 = window_id

        def update_region(_event: tk.Event | None = None) -> None:
            try:
                canvas.configure(scrollregion=canvas.bbox("all"))
            except tk.TclError:
                pass

        def fit_width(event: tk.Event) -> None:
            try:
                canvas.itemconfigure(window_id, width=max(1, int(event.width)))
                update_region()
            except tk.TclError:
                pass

        def wheel(event: tk.Event) -> str:
            try:
                delta = -1 if int(event.delta) > 0 else 1
                canvas.yview_scroll(delta * 3, "units")
            except (AttributeError, tk.TclError, ValueError):
                pass
            return "break"

        body.bind("<Configure>", update_region)
        canvas.bind("<Configure>", fit_width)
        canvas.bind("<MouseWheel>", wheel)
        body.bind("<MouseWheel>", wheel)

    def _refresh_run_plan(self) -> None:
        if not hasattr(self, "run_tree"):
            return
        self.run_tree.delete(*self.run_tree.get_children())
        if self._stage_progress_body_v89 is None:
            self._install_stage_progress_scroll_v89()
        body = self._stage_progress_body_v89
        if body is None:
            super()._refresh_run_plan()
            return
        for child in tuple(body.winfo_children()):
            child.destroy()
        self._stage_bars.clear()
        self._stage_values.clear()
        self._stage_order.clear()
        self._stage_run_buttons_v38.clear()
        self._pipeline_plan_rows_v38.clear()
        project = self.project
        if project is None:
            return
        try:
            plan = build_run_all_plan_v2(project)
        except Exception as exc:
            self._append_log(str(exc))
            return
        for row_index, stage in enumerate(plan["stages"]):
            key = str(stage["key"])
            self._pipeline_plan_rows_v38[key] = dict(stage)
            self.run_tree.insert("", "end", iid=key, text=stage["label"], values=(stage["status"], stage["description"]))
            label = ttk.Label(body, text=stage["label"])
            label.grid(row=row_index, column=0, sticky="w", padx=(0, 6), pady=2)
            bar = ttk.Progressbar(body, maximum=100.0, mode="determinate", style="Accent.Horizontal.TProgressbar", length=150)
            bar.grid(row=row_index, column=1, sticky="ew", pady=2)
            button = ttk.Button(body, text="Run", width=7, command=lambda stage_key=key: self._run_stage_v38(stage_key))
            button.grid(row=row_index, column=2, padx=(6, 0), pady=2)
            for widget in (label, bar, button):
                widget.bind("<MouseWheel>", lambda event, selected=self._stage_progress_canvas_v89: selected.yview_scroll((-1 if int(event.delta) > 0 else 1) * 3, "units") if selected is not None else None)
            self._stage_bars[key] = bar
            self._stage_values[key] = 0.0
            self._stage_order.append(key)
            self._stage_run_buttons_v38[key] = button
        self.overall_progress["value"] = 0.0
        self.overall_progress_label.set("Overall progress: ready")
        if self._stage_progress_canvas_v89 is not None:
            self.after_idle(lambda: self._stage_progress_canvas_v89.configure(scrollregion=self._stage_progress_canvas_v89.bbox("all")))

    def _install_horizontal_celdra_stage_v54(self) -> None:
        super()._install_horizontal_celdra_stage_v54()
        self._set_operation_title_v89()
        stage = self._celdra_avatar_pane_v51
        if stage is None:
            return
        for child in stage.winfo_children():
            if not isinstance(child, tk.Frame):
                continue
            labels = [item for item in child.winfo_children() if isinstance(item, tk.Label)]
            if len(labels) < 2:
                continue
            try:
                if str(labels[0].cget("textvariable")) != str(self._celdra_stage_title_v54):
                    continue
            except tk.TclError:
                continue
            labels[1].pack_forget()
            try:
                child.place_configure(height=32)
                labels[0].pack_configure(fill="x", padx=9, pady=(7, 5))
            except tk.TclError:
                pass
            break

    def _set_operation_title_v89(self) -> None:
        title = getattr(self, "_celdra_stage_title_v54", None)
        detail = getattr(self, "_celdra_stage_detail_v54", None)
        if title is not None:
            title.set("OPERATION: DRAGONEGG")
        if detail is not None:
            detail.set("")

    def _show_avatar_v51(self) -> None:
        super()._show_avatar_v51()
        self._set_operation_title_v89()

    def _show_dialogue_v51(self) -> None:
        super()._show_dialogue_v51()
        self._set_operation_title_v89()

    def _build_author_preview_tab_v74(self, parent: ttk.Frame) -> None:
        super()._build_author_preview_tab_v74(parent)
        self._install_text_editor_button_v89(parent, "preview")

    def _build_author_timeline_tab_v74(self, parent: ttk.Frame) -> None:
        super()._build_author_timeline_tab_v74(parent)
        self._install_text_editor_button_v89(parent, "timeline")

    def _install_text_editor_button_v89(self, parent: ttk.Frame, mode: str) -> None:
        bar = next((child for child in parent.winfo_children() if isinstance(child, ttk.LabelFrame) and str(child.cget("text")) == "Production RUN ALL playback"), None)
        if bar is None:
            return
        for child in bar.winfo_children():
            if isinstance(child, ttk.Button) and str(child.cget("text")) == "Text editor...":
                return
        for child in bar.winfo_children():
            if isinstance(child, ttk.Label):
                try:
                    if str(child.cget("textvariable")) == str(self._celdra_main_playback_status_v88):
                        child.grid_configure(column=5)
                except tk.TclError:
                    pass
        bar.columnconfigure(4, weight=0)
        bar.columnconfigure(5, weight=1)
        ttk.Button(bar, text="Text editor...", command=lambda selected=mode: self._open_text_editor_v89(selected)).grid(row=0, column=4, sticky="w", padx=(0, 8))

    def _open_text_editor_v89(self, mode: str) -> None:
        if self._celdra_text_editor_v89 is not None:
            try:
                self._celdra_text_editor_v89.destroy()
            except tk.TclError:
                pass
        selected_id = self._selected_author_event_id_v74() if mode == "timeline" else ""
        row = self._celdra_author_event_rows_v74.get(selected_id) if selected_id else None
        if mode == "timeline" and row is None:
            messagebox.showinfo("Celdra text editor", "Select an event first.", parent=self)
            return
        initial = str(row.get("text") or "") if row is not None else self._studio_text_value_v72()
        window = tk.Toplevel(self)
        self._celdra_text_editor_v89 = window
        window.title("Celdra dialogue / event text")
        window.geometry("720x360")
        window.transient(self)
        window.columnconfigure(0, weight=1)
        window.rowconfigure(1, weight=1)
        ttk.Label(window, text=f"Selected event: {selected_id}" if row is not None else "Preview / pose dialogue", anchor="w").grid(row=0, column=0, sticky="ew", padx=8, pady=(8, 4))
        editor = tk.Text(window, wrap="word", background="#101a28", foreground="#e2f5ff", insertbackground="#a9dcff", padx=10, pady=8)
        editor.grid(row=1, column=0, sticky="nsew", padx=8)
        editor.insert("1.0", initial)
        actions = ttk.Frame(window)
        actions.grid(row=2, column=0, sticky="ew", padx=8, pady=8)

        def save() -> None:
            value = editor.get("1.0", "end-1c")
            if row is None:
                if self._celdra_studio_text_v72 is not None:
                    self._celdra_studio_text_v72.delete("1.0", "end")
                    self._celdra_studio_text_v72.insert("1.0", value)
                self._render_author_preview_v74()
            else:
                updated = []
                for event_row in self._celdra_author_events_v74:
                    current = dict(event_row)
                    if str(current.get("id") or "") == selected_id:
                        current["text"] = value
                    updated.append(current)
                self._celdra_author_events_v74 = normalize_events(updated)
                self._refresh_author_event_tree_v74(select_id=selected_id)
                self._mini_seek_v84(float(row.get("at_ms") or 0))

        ttk.Button(actions, text="Save text", command=save).pack(side="left")
        ttk.Button(actions, text="Save + preview in main", command=lambda: (save(), self._preview_selected_event_main_v77() if row is not None else self._preview_current_in_main_v77())).pack(side="left", padx=(6, 0))
        ttk.Button(actions, text="Close", command=window.destroy).pack(side="right")
        editor.focus_set()

    @staticmethod
    def _is_duplicated_motion_row_v89(row: dict[str, Any]) -> bool:
        if str(row.get("action") or "").casefold() != "window":
            return False
        at_ms = int(row.get("at_ms") or 0)
        text = str(row.get("text") or "").strip().upper()
        identifier = str(row.get("id") or "")
        if not identifier.startswith("event-"):
            return False
        if 20_250 <= at_ms <= 26_000 and text == "CRACK ONE VIEWPORT 45% / CONSOLE 55%":
            return True
        return 118_000 <= at_ms <= 125_250 and text == "SHELL SIGNAL INSTABILITY DETECTED."

    @staticmethod
    def _obsolete_generated_runtime_v89(identifier: str) -> bool:
        if identifier.startswith("runtime-console-"):
            return True
        match = re.match(r"runtime-(\d{4})", identifier)
        return bool(match and int(match.group(1)) >= 8)

    @classmethod
    def _runtime_author_rows_v89(cls) -> list[dict[str, Any]]:
        base = 549_600
        rows = []
        for index, (delay, pose, text) in enumerate(cls.STORY_FILLER, start=1):
            stage, bubble_side = cls.POSE_STAGE.get(pose, ("right", "left"))
            common = {"sequence": "main", "speaker": "CELDRA", "asset": pose, "x": STAGE_X_V89[stage], "y": DRAGONGIRL_Y_V89, "scale": DRAGONGIRL_SCALE_V89, "window_percent": 56, "window_height_percent": 100, "window_y_percent": 0, "bubble_style": DRAGONGIRL_BUBBLE_STYLE_V89, **BUBBLE_GEOMETRY_V89[bubble_side]}
            rows.append({"id": f"v89-runtime-{index:02d}-pose", "at_ms": base + delay, "duration_ms": 650, "action": "pose", "text": "", "layout_override": True, **common})
            rows.append({"id": f"v89-runtime-{index:02d}-dialogue", "at_ms": base + delay + 650, "duration_ms": 0, "action": "bubble", "text": text, "layout_override": False, **common})
        for index, (delay, speaker, text) in enumerate(cls.INITIAL_CONSOLE_BANTER, start=1):
            rows.append({"id": f"v89-runtime-console-{index:02d}", "at_ms": base + delay, "duration_ms": 0, "sequence": "main", "action": "console", "speaker": speaker, "text": text, "layout_override": False, "notes": "Production BRAIN/CORE banter with live stage placeholders resolved at runtime."})
        end = base + cls.STORY_END_DELAY_MS
        rows.extend((
            {"id": "v89-runtime-completion-test-split", "at_ms": end, "sequence": "main", "action": "condition", "speaker": "CORE", "condition": "is_test", "true_sequence": "completion_test", "false_sequence": "completion_failure_check", "text": "Finish tests in Cool; otherwise inspect live RUN ALL state."},
            {"id": "v89-runtime-completion-failure-split", "at_ms": end + 100, "sequence": "completion_failure_check", "action": "condition", "speaker": "CORE", "condition": "run_all_failed", "true_sequence": "completion_failed", "false_sequence": "completion_check", "text": "Route failed RUN ALL before completion."},
            {"id": "v89-runtime-completion-success-split", "at_ms": end + 200, "sequence": "completion_check", "action": "condition", "speaker": "CORE", "condition": "run_all_complete", "true_sequence": "completion_success", "false_sequence": "still_running", "text": "Choose final Cool or continue waiting observations."},
        ))
        completion = (
            ("test", "completion_test", "cool", "right", "left", "Test sequence complete. Operation Dragonegg is stable enough for one clean run."),
            ("failed", "completion_failed", "sad", "left", "right", "RUN ALL failed. I am leaving the evidence visible and judging the responsible subsystem quietly."),
            ("success", "completion_success", "cool", "right", "left", "RUN ALL complete. CCSF extracted, outputs indexed, and Operation Dragonegg survived first contact."),
            ("waiting", "still_running", "smile", "right", "left", "Still running. I'll keep watch from here and try not to annex any more interface."),
        )
        for index, (name, sequence, pose, stage, bubble_side, text) in enumerate(completion):
            common = {"sequence": sequence, "speaker": "CELDRA", "asset": pose, "x": STAGE_X_V89[stage], "y": DRAGONGIRL_Y_V89, "scale": DRAGONGIRL_SCALE_V89, "window_percent": 56, "window_height_percent": 100, "window_y_percent": 0, "bubble_style": DRAGONGIRL_BUBBLE_STYLE_V89, **BUBBLE_GEOMETRY_V89[bubble_side]}
            rows.append({"id": f"v89-runtime-completion-{name}-pose", "at_ms": end + 300 + index * 20, "duration_ms": 650, "action": "pose", "text": "", "layout_override": True, **common})
            rows.append({"id": f"v89-runtime-completion-{name}-dialogue", "at_ms": end + 950 + index * 20, "duration_ms": 0, "action": "bubble", "text": text, "layout_override": False, **common})
        return [normalize_event(row, index) for index, row in enumerate(rows)]

    def _apply_dragongirl_authoring_profile_v87(self) -> None:
        super()._apply_dragongirl_authoring_profile_v87()
        result = []
        generated_ids = {str(row.get("id") or "") for row in MOTION_ROWS_V89}
        for row in self._celdra_author_events_v74:
            current = dict(row)
            identifier = str(current.get("id") or "")
            if identifier in generated_ids or identifier.startswith("v89-runtime-") or self._is_duplicated_motion_row_v89(current) or self._obsolete_generated_runtime_v89(identifier):
                continue
            asset = str(current.get("asset") or "").casefold()
            if int(current.get("at_ms") or 0) >= 506_000 and asset in self.DRAGONGIRL_ASSETS:
                current["bubble_style"] = DRAGONGIRL_BUBBLE_STYLE_V89
                if asset == "shy":
                    current.update({"x": STAGE_X_V89["center"], "y": SHY_Y_V89, "scale": SHY_SCALE_V89, **BUBBLE_GEOMETRY_V89["above"]})
                else:
                    current["y"] = DRAGONGIRL_Y_V89
                    current["scale"] = DRAGONGIRL_SCALE_V89
            result.append(current)
        result.extend(dict(row) for row in MOTION_ROWS_V89)
        result.extend(self._runtime_author_rows_v89())
        self._celdra_author_events_v74 = normalize_events(result)
        self._celdra_author_event_serial_v74 = max(int(getattr(self, "_celdra_author_event_serial_v74", 0)), len(self._celdra_author_events_v74))

    def _apply_author_project_payload_v74(self, payload: dict[str, Any]) -> None:
        super()._apply_author_project_payload_v74(payload)
        self._apply_dragongirl_authoring_profile_v87()
        self._refresh_author_event_tree_v74()

    def _author_project_payload_v74(self) -> dict[str, Any]:
        self._apply_dragongirl_authoring_profile_v87()
        payload = super()._author_project_payload_v74()
        metadata = payload.setdefault("metadata", {})
        if isinstance(metadata, dict):
            metadata["gui_version"] = "V89"
            metadata["operation_title"] = "OPERATION: DRAGONEGG"
            metadata["run_all_viewports_locked"] = True
            metadata["stage_progress_scrollbar"] = True
            metadata["compact_motion_controllers"] = True
            metadata["console_whiteout"] = True
            metadata["canonical_dragongirl_staging"] = {"shy": {"scale": SHY_SCALE_V89, "avatar_y": SHY_Y_V89, "avatar_x": 0}, "other_png_emotes": {"scale": DRAGONGIRL_SCALE_V89, "avatar_y": DRAGONGIRL_Y_V89}, "side_stage_x": {"left": -170, "right": 170}, "bubble_style": DRAGONGIRL_BUBBLE_STYLE_V89}
        return payload

    def _cancel_crack_pulse_v89(self) -> None:
        if self._celdra_crack_pulse_after_v89 is not None:
            try:
                self.after_cancel(self._celdra_crack_pulse_after_v89)
            except tk.TclError:
                pass
            self._celdra_crack_pulse_after_v89 = None

    def _start_crack_pulse_v89(self, values: tuple[float, ...], *, interval_ms: int = 250) -> None:
        self._cancel_crack_pulse_v89()
        index = 0
        def tick() -> None:
            nonlocal index
            self._celdra_crack_pulse_after_v89 = None
            if index >= len(values):
                return
            self._set_stage_fraction_v54(values[index])
            index += 1
            if index < len(values):
                self._celdra_crack_pulse_after_v89 = self.after(self._scaled_runtime_ms_v88(interval_ms), tick)
        tick()

    def _start_instability_shake_v89(self) -> None:
        if self._celdra_instability_shake_active_v89:
            return
        pane = self.celdra_visual_split_v50
        if pane is None:
            return
        self._cancel_crack_pulse_v89()
        self._celdra_instability_shake_active_v89 = True
        self._celdra_instability_shake_phase_v89 = 0
        try:
            total = max(1, pane.winfo_width())
            self._celdra_instability_base_fraction_v89 = pane.sashpos(0) / total
        except (AttributeError, tk.TclError):
            self._celdra_instability_base_fraction_v89 = 0.17
        started = time.monotonic()
        pattern = (0, 1, -1, 2, -2, 3, -3, 1, -2, 2, -1)
        def tick() -> None:
            self._celdra_instability_shake_after_v89 = None
            if not self._celdra_instability_shake_active_v89:
                return
            elapsed = (time.monotonic() - started) / max(0.05, self._scaled_runtime_ms_v88(45_000) / 1000.0)
            strength = min(1.0, 0.35 + elapsed * 0.85)
            phase = self._celdra_instability_shake_phase_v89
            direction = pattern[phase % len(pattern)]
            self._celdra_viewport_shake_x_v89 = round(direction * (2 + 4 * strength))
            self._celdra_viewport_shake_y_v89 = round(pattern[(phase + 4) % len(pattern)] * (1 + 2 * strength))
            try:
                width = max(1, pane.winfo_width())
                sash_jitter = round(direction * (6 + 13 * strength))
                pane.sashpos(0, max(18, min(width - 36, int(width * self._celdra_instability_base_fraction_v89) + sash_jitter)))
            except (AttributeError, tk.TclError):
                pass
            self._celdra_instability_shake_phase_v89 += 1
            self._redraw_celdra_avatar_v50()
            self._celdra_instability_shake_after_v89 = self.after(max(12, self._scaled_runtime_ms_v88(46)), tick)
        tick()

    def _stop_instability_shake_v89(self, *, restore_stage: bool = False) -> None:
        self._celdra_instability_shake_active_v89 = False
        if self._celdra_instability_shake_after_v89 is not None:
            try:
                self.after_cancel(self._celdra_instability_shake_after_v89)
            except tk.TclError:
                pass
            self._celdra_instability_shake_after_v89 = None
        self._celdra_viewport_shake_x_v89 = 0
        self._celdra_viewport_shake_y_v89 = 0
        if restore_stage:
            self._set_stage_fraction_v54(self._celdra_instability_base_fraction_v89)
        if hasattr(self, "celdra_avatar_canvas_v50"):
            self._redraw_celdra_avatar_v50()

    def _emit_timeline_event_v51(self, event: Any) -> None:
        action = str(getattr(event, "action", "") or "").casefold()
        text = str(getattr(event, "text", "") or "")
        speaker = str(getattr(event, "speaker", "") or "").upper()
        phase = str(getattr(event, "avatar_phase", "") or "").casefold()
        if action == "console" and speaker == "CELDRA" and text.upper() in {"INITIALIZED", "ONLINE"} and self._celdra_whiteout_active_v89:
            self._append_whiteout_celdra_line_v89(text.upper())
            if text.upper() == "ONLINE":
                self._remember_after_v49(self._scaled_runtime_ms_v88(850), self._start_console_restore_v89)
            return
        super()._emit_timeline_event_v51(event)
        if action == "avatar" and phase == "crack_one":
            values = tuple(0.50 if index % 2 == 0 else 0.45 for index in range(22)) + (0.40,)
            self._remember_after_v49(self._scaled_runtime_ms_v88(820), lambda: self._start_crack_pulse_v89(values))
        elif action == "avatar" and phase == "crack_two":
            values = tuple(0.535 if index % 2 == 0 else 0.485 for index in range(16)) + (0.49,)
            self._remember_after_v49(self._scaled_runtime_ms_v88(720), lambda: self._start_crack_pulse_v89(values, interval_ms=220))
        elif action == "console" and "SHELL SIGNAL INSTABILITY DETECTED" in text.upper():
            self._start_instability_shake_v89()

    def _set_egg_glitch_v61(self, level: int) -> None:
        super()._set_egg_glitch_v61(level)
        if int(level) >= 3 and not self._celdra_whiteout_active_v89:
            self._start_console_alarm_v64()

    def _tick_console_alarm_v64(self) -> None:
        self._celdra_console_alarm_after_v64 = None
        if self._celdra_whiteout_active_v89:
            return
        widget = self._celdra_console_v49
        if widget is None:
            return
        palettes = (("#000000", "#ff2638"), ("#4a0008", "#000000"), ("#090000", "#c90020"), ("#8b0014", "#000000"))
        background, foreground = palettes[self._celdra_console_alarm_phase_v64 % len(palettes)]
        self._celdra_console_alarm_phase_v64 += 1
        try:
            widget.configure(background=background, foreground=foreground, insertbackground=foreground)
        except tk.TclError:
            return
        self._celdra_console_alarm_after_v64 = self.after(max(28, self._scaled_runtime_ms_v88(105)), self._tick_console_alarm_v64)

    def _console_widgets_v89(self) -> list[tk.Text]:
        result = []
        seen = set()
        for widget in (getattr(self, "run_log", None), getattr(self, "_celdra_console_v49", None)):
            if not isinstance(widget, tk.Text) or str(widget) in seen:
                continue
            seen.add(str(widget))
            result.append(widget)
        return result

    def _rgb_v89(self, color: str, fallback: tuple[int, int, int]) -> tuple[int, int, int]:
        try:
            red, green, blue = self.winfo_rgb(str(color))
            return red // 257, green // 257, blue // 257
        except tk.TclError:
            return fallback

    @staticmethod
    def _hex_v89(rgb: tuple[float, float, float]) -> str:
        values = [max(0, min(255, round(value))) for value in rgb]
        return f"#{values[0]:02x}{values[1]:02x}{values[2]:02x}"

    def _blend_v89(self, start: str, end: str, progress: float) -> str:
        first = self._rgb_v89(start, (16, 21, 29))
        second = self._rgb_v89(end, (255, 255, 255))
        amount = max(0.0, min(1.0, float(progress)))
        return self._hex_v89(tuple(first[index] + (second[index] - first[index]) * amount for index in range(3)))

    def _capture_console_palette_v89(self) -> None:
        if self._celdra_whiteout_saved_v89:
            return
        for widget in self._console_widgets_v89():
            tags = {}
            try:
                for tag in widget.tag_names():
                    value = str(widget.tag_cget(tag, "foreground") or "")
                    if value:
                        tags[str(tag)] = value
                self._celdra_whiteout_saved_v89[str(widget)] = {"widget": widget, "background": str(widget.cget("background")), "foreground": str(widget.cget("foreground")), "insertbackground": str(widget.cget("insertbackground")), "tags": tags}
            except tk.TclError:
                continue

    def _animate_console_palette_v89(self, *, restoring: bool, duration_ms: int) -> None:
        self._capture_console_palette_v89()
        self._celdra_whiteout_token_v89 += 1
        token = self._celdra_whiteout_token_v89
        if self._celdra_whiteout_after_v89 is not None:
            try:
                self.after_cancel(self._celdra_whiteout_after_v89)
            except tk.TclError:
                pass
            self._celdra_whiteout_after_v89 = None
        started = time.monotonic()
        duration_ms = max(1, int(duration_ms))
        def tick() -> None:
            self._celdra_whiteout_after_v89 = None
            if token != self._celdra_whiteout_token_v89:
                return
            progress = min(1.0, (time.monotonic() - started) * 1000.0 / duration_ms)
            for saved in tuple(self._celdra_whiteout_saved_v89.values()):
                widget = saved["widget"]
                try:
                    background = self._blend_v89("#ffffff", saved["background"], progress) if restoring else self._blend_v89(saved["background"], "#ffffff", progress)
                    foreground = self._blend_v89("#ffffff", saved["foreground"], progress) if restoring else self._blend_v89(saved["foreground"], "#ffffff", progress)
                    widget.configure(background=background, foreground=foreground, insertbackground=foreground)
                    for tag, target in dict(saved.get("tags") or {}).items():
                        widget.tag_configure(tag, foreground=self._blend_v89("#ffffff" if restoring else target, target if restoring else "#ffffff", progress))
                    for tag in widget.tag_names():
                        if str(tag).startswith("v89_whiteout_celdra_"):
                            widget.tag_configure(tag, foreground=self._blend_v89("#000000", saved["foreground"], progress) if restoring else "#000000", font=("Consolas", 12, "bold"))
                except tk.TclError:
                    continue
            if progress < 1.0:
                self._celdra_whiteout_after_v89 = self.after(24, tick)
            elif restoring:
                self._finish_console_restore_v89()
        tick()

    def _start_console_whiteout_v89(self) -> None:
        self._celdra_whiteout_active_v89 = True
        self._animate_console_palette_v89(restoring=False, duration_ms=self._scaled_runtime_ms_v88(4_250))

    def _append_whiteout_celdra_line_v89(self, text: str) -> None:
        widget = self._celdra_console_v49
        start = None
        if widget is not None:
            try:
                start = widget.index("end-1c")
            except tk.TclError:
                start = None
        self._append_console_v49(f"[CELDRA] {text}")
        if widget is None or start is None:
            return
        self._celdra_whiteout_line_serial_v89 += 1
        tag = f"v89_whiteout_celdra_{self._celdra_whiteout_line_serial_v89}"
        try:
            end = widget.index("end-1c")
            widget.configure(state="normal")
            widget.tag_add(tag, start, end)
            widget.tag_configure(tag, foreground="#ffffff", font=("Consolas", 12, "bold"))
            widget.see("end")
            widget.configure(state="disabled")
        except tk.TclError:
            try:
                widget.configure(state="disabled")
            except tk.TclError:
                pass
            return
        started = time.monotonic()
        duration_ms = self._scaled_runtime_ms_v88(1_050)
        def tick() -> None:
            progress = min(1.0, (time.monotonic() - started) * 1000.0 / max(1, duration_ms))
            try:
                widget.tag_configure(tag, foreground=self._blend_v89("#ffffff", "#000000", progress), font=("Consolas", 12, "bold"))
            except tk.TclError:
                return
            if progress < 1.0:
                self.after(24, tick)
        tick()

    def _start_console_restore_v89(self) -> None:
        if self._celdra_whiteout_active_v89:
            self._animate_console_palette_v89(restoring=True, duration_ms=self._scaled_runtime_ms_v88(1_850))

    def _finish_console_restore_v89(self) -> None:
        for saved in tuple(self._celdra_whiteout_saved_v89.values()):
            widget = saved["widget"]
            try:
                widget.configure(background=saved["background"], foreground=saved["foreground"], insertbackground=saved["insertbackground"])
                for tag, color in dict(saved.get("tags") or {}).items():
                    widget.tag_configure(tag, foreground=color)
                for tag in widget.tag_names():
                    if str(tag).startswith("v89_whiteout_celdra_"):
                        widget.tag_configure(tag, foreground=saved["foreground"], font=("Consolas", 10, "bold"))
            except tk.TclError:
                continue
        self._celdra_whiteout_saved_v89.clear()
        self._celdra_whiteout_active_v89 = False
        self._celdra_whiteout_after_v89 = None

    def _restore_console_palette_v89(self) -> None:
        self._celdra_whiteout_token_v89 += 1
        if self._celdra_whiteout_after_v89 is not None:
            try:
                self.after_cancel(self._celdra_whiteout_after_v89)
            except tk.TclError:
                pass
            self._celdra_whiteout_after_v89 = None
        self._finish_console_restore_v89()

    def _start_energy_hatch_v63(self) -> None:
        self._cancel_crack_pulse_v89()
        self._stop_instability_shake_v89(restore_stage=False)
        super()._start_energy_hatch_v63()
        self._stop_console_alarm_v64()
        self._start_console_whiteout_v89()

    def _set_stage_position_v87(self, stage: str, bubble_side: str) -> None:
        super()._set_stage_position_v87(stage, bubble_side)
        self._celdra_external_offset_x_v65 = STAGE_X_V89[stage]
        self._celdra_external_offset_y_v58 = DRAGONGIRL_Y_V89

    def _begin_shy_reveal_v64(self) -> None:
        canvas = self.celdra_avatar_canvas_v50
        canvas_height = canvas.winfo_height() if canvas is not None else 420
        self._celdra_runtime_bubble_side_v87 = "above"
        self._celdra_runtime_stage_v87 = "center"
        self._celdra_external_offset_x_v65 = STAGE_X_V89["center"]
        if not self._load_takeover_reaction_v58("shy"):
            return
        self._celdra_shy_rest_offset_v64 = SHY_Y_V89
        self._celdra_external_offset_y_v58 = max(320, canvas_height + 90)
        PublicFragmenterAppV54._animate_stage_fraction_v54(self, 0.50, self._scaled_runtime_ms_v88(1_650))
        self._redraw_celdra_avatar_v50()
        self._remember_after_v49(self._scaled_runtime_ms_v88(260), self._start_shy_creep_v58)

    def _start_shy_creep_v58(self) -> None:
        if self._celdra_creep_after_v58 is not None:
            try:
                self.after_cancel(self._celdra_creep_after_v58)
            except tk.TclError:
                pass
        start = max(1, int(self._celdra_external_offset_y_v58 or 0))
        target = SHY_Y_V89
        distance = max(1, start - target)
        started = time.monotonic()
        duration_ms = self._scaled_runtime_ms_v88(12_000)
        def tick() -> None:
            elapsed = (time.monotonic() - started) * 1000.0
            fraction = min(1.0, elapsed / max(1, duration_ms))
            progress = self._shy_progress_v63(fraction)
            self._celdra_external_offset_y_v58 = round(start - distance * progress)
            self._redraw_celdra_avatar_v50()
            if fraction < 1.0:
                self._celdra_creep_after_v58 = self.after(16, tick)
            else:
                self._celdra_external_offset_y_v58 = target
                self._celdra_creep_after_v58 = None
                self._redraw_celdra_avatar_v50()
        tick()

    def _format_runtime_text_v89(self, text: str) -> str:
        stage = str(getattr(self, "_celdra_last_run_stage_v70", "waiting") or "waiting")
        kind = str(getattr(self, "_celdra_last_run_kind_v70", "idle") or "idle")
        status = str(getattr(self, "_celdra_last_run_status_v70", "pending") or "pending")
        return str(text or "").format(stage=stage.replace("_", " ").upper(), kind=kind.replace("_", " ").upper(), status=status.replace("_", " ").upper())

    def _runtime_filler_pose_v87(self, pose: str, text: str) -> None:
        super()._runtime_filler_pose_v87(pose, self._format_runtime_text_v89(text))

    def _runtime_console_banter_v88(self, speaker: str, text: str) -> None:
        super()._runtime_console_banter_v88(speaker, self._format_runtime_text_v89(text))

    def _start_placeholder_runtime_v70(self) -> None:
        if self._celdra_placeholder_started_v70:
            return
        self._celdra_placeholder_started_v70 = True
        self._hide_speech_bubble_v58()
        self._runtime_pose_v70("confused", self._assessment_text_v70())
        if self._celdra_pipeline_success_v70:
            self._show_completion_cool_v70()
            return
        for delay, pose, text in self.STORY_FILLER:
            self._remember_after_v49(self._scaled_runtime_ms_v88(delay), lambda selected_pose=pose, selected_text=text: self._runtime_filler_pose_v87(selected_pose, selected_text))
        for delay, speaker, text in self.INITIAL_CONSOLE_BANTER:
            self._remember_after_v49(self._scaled_runtime_ms_v88(delay), lambda selected_speaker=speaker, selected_text=text: self._runtime_console_banter_v88(selected_speaker, selected_text))
        self._remember_after_v49(self._scaled_runtime_ms_v88(self.STORY_END_DELAY_MS), self._runtime_wait_or_complete_v87)

    def _redraw_celdra_avatar_v50(self) -> None:
        super()._redraw_celdra_avatar_v50()
        canvas = getattr(self, "celdra_avatar_canvas_v50", None)
        if canvas is not None and self._celdra_instability_shake_active_v89:
            try:
                canvas.move("all", self._celdra_viewport_shake_x_v89, self._celdra_viewport_shake_y_v89)
            except tk.TclError:
                pass
        self._set_operation_title_v89()

    def _timeline_state_at_v84(self, target_ms: float) -> tuple[dict[str, Any], str]:
        state, active_id = super()._timeline_state_at_v84(target_ms)
        time_ms = float(target_ms)
        state["v89_crack_pulse"] = (20_000 <= time_ms < 26_000) or (40_000 <= time_ms < 44_500)
        state["v89_instability_shake"] = 118_000 <= time_ms < 163_000
        if 163_000 <= time_ms < 167_250:
            state["v89_whiteout"] = (time_ms - 163_000) / 4_250.0
        elif 167_250 <= time_ms < 176_850:
            state["v89_whiteout"] = 1.0
        elif 176_850 <= time_ms < 178_700:
            state["v89_whiteout"] = 1.0 - (time_ms - 176_850) / 1_850.0
        else:
            state["v89_whiteout"] = 0.0
        return state, active_id

    def _render_timeline_mini_v84(self, state: dict[str, Any] | None = None) -> None:
        if state is None:
            state, _active = self._timeline_state_at_v84(self._celdra_mini_playhead_ms_v84)
        super()._render_timeline_mini_v84(state)
        canvas = self._celdra_mini_canvas_v84
        if canvas is None:
            return
        width = max(420, canvas.winfo_width())
        height = max(245, canvas.winfo_height())
        if state.get("v89_crack_pulse"):
            canvas.create_text(8, height - 20, text="CRACK PULSE CONTROLLER ACTIVE", anchor="sw", fill="#ffd267", font=("Consolas", 7, "bold"))
        if state.get("v89_instability_shake"):
            canvas.create_rectangle(2, 2, width - 2, height - 2, outline="#ff2638", width=3, dash=(3, 2))
            canvas.create_text(width // 2, 38, text="SHELL SIGNAL INSTABILITY / VIEWPORT SHAKE", anchor="center", fill="#ff5964", font=("Consolas", 8, "bold"))
        whiteout = max(0.0, min(1.0, float(state.get("v89_whiteout") or 0.0)))
        if whiteout > 0:
            stipple = "gray25" if whiteout < 0.45 else "gray50" if whiteout < 0.8 else ""
            kwargs = {"fill": "#ffffff", "outline": "", "tags": "v89_mini_whiteout"}
            if stipple:
                kwargs["stipple"] = stipple
            try:
                canvas.create_rectangle(0, 0, width, height, **kwargs)
            except tk.TclError:
                kwargs.pop("stipple", None)
                canvas.create_rectangle(0, 0, width, height, **kwargs)
            time_ms = float(state.get("time_ms") or self._celdra_mini_playhead_ms_v84)
            lines = []
            if time_ms >= 172_000:
                lines.append("[CELDRA] INITIALIZED")
            if time_ms >= 176_000:
                lines.append("[CELDRA] ONLINE")
            if lines:
                canvas.create_text(width // 2, height // 2, text="\n\n".join(lines), anchor="center", fill="#000000", font=("Consolas", 13, "bold"))

    def _prepare_first_run_surface_v51(self) -> None:
        self._cancel_crack_pulse_v89()
        self._stop_instability_shake_v89(restore_stage=False)
        self._restore_console_palette_v89()
        super()._prepare_first_run_surface_v51()
        self._set_operation_title_v89()

    def _cancel_celdra_cues_v49(self) -> None:
        self._cancel_crack_pulse_v89()
        self._stop_instability_shake_v89(restore_stage=False)
        self._restore_console_palette_v89()
        super()._cancel_celdra_cues_v49()


def main() -> int:
    app = PublicFragmenterAppV89()
    app.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
